spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: default
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        default_schema: auth
        dialect: org.hibernate.dialect.PostgreSQLDialect
        properties.hibernate.temp.use_jdbc_metadata_defaults: false
        jdbc.lob.non_contextual_creation: true
        show_sql: true